-- figure out how to use harpoon
-- Set up up and down page keep cursor in center
-- Rewatch primeagen and pull out the good key bindings make notes on favorites
-- Primeagen's copy trick for between browsers I think it was <C-Y>
-- Prime's J doens't move cursor
-- Prime's undo tree
-- Prime's only show next search item
-- prime did something neat with his LSP like defaulted to get def of LSP but if not available use vim default :
-- install fugitive and figure out how to use git stuff.
